#ifndef CONSTANTS_QT_H
#define CONSTANTS_QT_H

#define USES_CONSTANTS_QT

#include "constants.h"
#include <QString>

// COMMANDS
enum MQTT_CMDS {
    START_PREHEAT = MQTT_CMD_START_PREHEAT
};

// ERRORS
enum MQTT_ERRORS {
    ERRORS_RELAYS = MQTT_PATH_ERRORS_RELAYS
};

static QString ERRORS_LABELS[] = {
    ERRORS_LABEL_RELAYS
};

// SETTINGS
enum MQTT_SETTINGS {
    SETTINGS_PREHEAT_FROM = MQTT_PATH_SETTINGS_PREHEAT_FROM,
    SETTINGS_PREHEAT_TO = MQTT_PATH_SETTINGS_PREHEAT_TO,
    SETTINGS_PREHEAT_HC_TEMP = MQTT_PATH_SETTINGS_PREHEAT_HC_TEMP,
    SETTINGS_PREHEAT_WATER_TEMP = MQTT_PATH_SETTINGS_PREHEAT_WATER_TEMP
};

static QString SETTINGS_LABELS[] = {
    SETTINGS_LABEL_PREHEAT_FROM,
    SETTINGS_LABEL_PREHEAT_TO,
    SETTINGS_LABEL_PREHEAT_HC_TEMP,
    SETTINGS_LABEL_PREHEAT_WATER_TEMP
};

// TEMPERATURES
enum MQTT_TEMPS {
    TEMPS_HC = MQTT_PATH_TEMPS_HC,
    TEMPS_TANK = MQTT_PATH_TEMPS_TANK,
    TEMPS_WATER = MQTT_PATH_TEMPS_WATER
};

static QString TEMPS_LABELS[] = {
    TEMPS_LABEL_HC,
    TEMPS_LABEL_TANK,
    TEMPS_LABEL_WATER
};

// RELAYS
enum MQTT_RELAYS {
    RELAYS_HC_PUMP = MQTT_PATH_RELAYS_HC_PUMP,
    RELAYS_WATER_PUMP = MQTT_PATH_RELAYS_WATER_PUMP
};

static QString RELAYS_LABELS[] {
    RELAYS_LABEL_HC_PUMP,
    RELAYS_LABEL_WATER_PUMP
};

#endif // CONSTANTS_QT_H
